### ISSUE TITLE
Unexpected tab leave warning when timed out

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#139]
### Description
If you time out during a game you're playing, browser will ask you whether to stay or leave the page.

### Reproduction
1. Start a quick play game
2. During quick play game upload a large file idk
3. You will get a timeout message
4. After confirming, tab quit warning will appear

### Expected behavior
No tab quit warning should appear.

**Comment by o5k** [comment]
Fixed in next patch.

**Comment by Wirtualnosc** [comment]
still happens with following error:
> CONNECTION ERROR
> the server has disconnected you.
> REASON: timeout: no data received for 15096 milliseconds
> please check your internet connection. if this seems to be an error, please report it
to reproduce - I played a game against myself with 0 gravity and left one tab open in the background, while I played with the other one

**Comment by o5k** [comment]
ok, will be truly fixed in alpha
